# Generated by Django 4.1.4 on 2023-01-07 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('specialization', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('specialization', models.CharField(max_length=20)),
                ('opd_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
