# Generated by Django 4.1.4 on 2023-01-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=10)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalapp.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IpdPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=10)),
                ('ward', models.CharField(max_length=20)),
                ('medicine_charges', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bloodcheck_charges', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('radiology_charges', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('injection_charges', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('laundary_charges', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('misc_charges', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bill_paid', models.BooleanField(default=False)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('discharge_date', models.DateField()),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalapp.doctor')),
                ('nurses', models.ManyToManyField(to='hospitalapp.nurse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
