# Generated by Django 4.1.4 on 2023-01-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_opdpatient_ipdpatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdpatient',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
