from django.urls import path
from . import department, nurse, staff, doctor, opdpatient, ipdpatient

urlpatterns = [
    path('department/', department.get_all, name='get_all_department'),
    path('department/create/', department.create_department, name='create_department'),
    path('department/get/<int:id>', department.get_by_id, name='get_department_by_id'),
    path('department/edit/<int:id>', department.edit_department, name='edit_department'),
    path('department/delete/<int:id>', department.delete_department, name='delete_department'),
    path('department/doctors/<int:id>', department.get_all_doctors_in_a_department, name='get_doctors_in_department'),
    path('department/nurses/<int:id>', department.get_all_nurses_in_a_department, name='get_nurses_in_department'),
    path('staff/', staff.get_all_staff, name='get_all_staff'),
    path('staff/create/', staff.create_staff, name='create_staff'),
    path('staff/get/<int:id>', staff.get_staff_by_id, name='get_staff_by_id'),
    path('staff/edit/<int:id>', staff.edit_staff, name='edit_staff'),
    path('staff/delete/<int:id>', staff.delete_staff, name='delete_staff'),
    path('nurse/', nurse.get_all_nurse, name='get_all_nurse'),
    path('nurse/create/', nurse.create_nurse, name='create_nurse'),
    path('nurse/get/<int:id>', nurse.get_nurse_by_id, name='get_nurse_by_id'),
    path('nurse/edit/<int:id>', nurse.edit_nurse, name='edit_nurse'),
    path('nurse/delete/<int:id>', nurse.delete_nurse, name='delete_nurse'),
    path('nurse/ipdpatient/<int:id>', nurse.get_all_ipdpatients_of_nurse, name='get_ipdpatients_of_nurse'),
    path('doctor/', doctor.get_all_doctor, name='get_all_doctor'),
    path('doctor/create/', doctor.create_doctor, name='create_doctor'),
    path('doctor/get/<int:id>', doctor.get_doctor_by_id, name='get_doctor_by_id'),
    path('doctor/edit/<int:id>', doctor.edit_doctor, name='edit_doctor'),
    path('doctor/delete/<int:id>', doctor.delete_doctor, name='delete_doctor'),
    path('doctor/opdpatient/<int:id>', doctor.get_all_opdpatients_of_doctor, name='get_opdpatients_of_doctor'),
    path('doctor/ipdpatient/<int:id>', doctor.get_all_ipdpatients_of_doctor, name='get_ipdpatients_of_doctor'),
    path('opdpatient/', opdpatient.get_all_opdpatient, name='get_all_opdpatient'),
    path('opdpatient/create/', opdpatient.create_opdpatient, name='create_opdpatient'),
    path('opdpatient/get/<int:id>', opdpatient.get_opdpatient_by_id, name='get_opdpatient_by_id'),
    path('opdpatient/edit/<int:id>', opdpatient.edit_opdpatient, name='edit_opdpatient'),
    path('opdpatient/delete/<int:id>', opdpatient.delete_opdpatient, name='delete_opdpatient'),
    path('ipdpatient/', ipdpatient.get_all_ipdpatient, name='get_all_ipdpatient'),
    path('ipdpatient/create/', ipdpatient.create_ipdpatient, name='create_ipdpatient'),
    path('ipdpatient/get/<int:id>', ipdpatient.get_ipdpatient_by_id, name='get_ipdpatient_by_id'),
    path('ipdpatient/edit/<int:id>', ipdpatient.edit_ipdpatient, name='edit_ipdpatient'),
    path('ipdpatient/delete/<int:id>', ipdpatient.delete_ipdpatient, name='delete_ipdpatient'),
    path('ipdpatient/totalbill/<int:id>', ipdpatient.total_bill_amount, name='total_bill'),
    path('ipdpatient/discharge/<int:id>', ipdpatient.discharge, name='discharge'),
    path('ipdpatient/updatecharges/<int:id>', ipdpatient.update_charges, name='update_charges'),
]